### ISSUE TITLE
[Public page] The labels of the filters are not responsive

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/harta-help2help-ucraina#17]
<img width="1083" alt="Screenshot 2023-08-03 at 14 48 24" src="https://github.com/code4romania/harta-help2help-ucraina/assets/111346300/f3342830-3c4e-45e8-97e7-cb4c5e75e930">

**Comment by vilenbejenaru** [comment]
The label's font-size changes on different media.
Because of too long text for label, it is difficult to be adapted as expected in current design.

It can be fixed by increasing input size and create an extra-line

![image](https://github.com/code4romania/harta-help2help-ucraina/assets/70964449/d4325752-d7f3-4227-8da6-8fb46aa3d823)
